# Generated by Django 5.0 on 2023-12-27 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE oauth2_provider_application 
            DROP FOREIGN KEY oauth2_provider_appl_user_id_79829054_fk_mealmaste;
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE oauth2_provider_application 
            ADD CONSTRAINT new_foreign_key_name
            FOREIGN KEY (tai_khoan_id)
            REFERENCES mealmaster_taikhoan (id);
            """
        ),
    ]