# Generated by Django 5.0 on 2024-01-07 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binhluan',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='binhluanimg'),
        ),
        migrations.AddField(
            model_name='menu',
            name='nguoi_dung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='binhluan',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='binhluanimg'),
        ),
    ]
