# Generated by Django 5.0.1 on 2024-01-16 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealmaster', '0002_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='binhluan',
            name='mon_an_binh_luan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mealmaster.monan'),
        ),
    ]
