# Generated by Django 5.0.1 on 2024-01-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealmaster', '0003_binhluan_mon_an_binh_luan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoidiem',
            name='thoi_gian_bat_dau',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='thoidiem',
            name='thoi_gian_ket_thuc',
            field=models.TimeField(),
        ),
    ]
