# Generated by Django 5.0.1 on 2024-01-16 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealmaster', '0006_alter_thoigianban_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoigianban',
            name='mon_an',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mealmaster.monan'),
        ),
    ]
