# Generated by Django 5.0.1 on 2024-01-17 08:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealmaster', '0008_alter_monan_gia_mon_an_alter_monan_hinh_anh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
