# Generated by Django 5.0.1 on 2024-01-17 09:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealmaster', '0009_alter_taikhoan_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monan',
            name='hinh_anh',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='hinh_anh'),
        ),
    ]
