# Generated by Django 5.0.1 on 2024-01-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealmaster', '0011_menu_hinh_anh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='trang_thai',
            field=models.BooleanField(default=True),
        ),
    ]
