# Generated by Django 5.0.1 on 2024-01-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealmaster', '0012_alter_menu_trang_thai'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
