# Generated by Django 5.0.1 on 2024-01-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealmaster', '0014_loaithucan_hinh_anh'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitiethoadon',
            name='so_luong',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
