# Generated by Django 5.0.1 on 2024-02-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealmaster', '0019_payment_vnpay_cartitemids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_vnpay',
            name='mon_an',
        ),
    ]
