# Generated by Django 5.0.1 on 2024-02-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealmaster', '0020_remove_payment_vnpay_mon_an'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietHoaDonVNPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealmaster.payment_vnpay')),
                ('mon_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealmaster.monan')),
            ],
        ),
        migrations.AddField(
            model_name='payment_vnpay',
            name='mon_an',
            field=models.ManyToManyField(related_name='hoadon_vnpay', through='mealmaster.ChiTietHoaDonVNPay', to='mealmaster.monan'),
        ),
    ]
