# Generated by Django 5.0.1 on 2024-02-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealmaster', '0021_chitiethoadonvnpay_payment_vnpay_mon_an'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_vnpay',
            name='ngay_thanh_toan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
