# Generated by Django 5.0.1 on 2024-02-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealmaster', '0022_payment_vnpay_ngay_thanh_toan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_vnpay',
            name='ngay_thanh_toan',
        ),
    ]
