# Generated by Django 5.0.1 on 2024-02-28 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealmaster', '0023_remove_payment_vnpay_ngay_thanh_toan'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitiethoadonvnpay',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mealmaster.menu'),
        ),
        migrations.AddField(
            model_name='payment_vnpay',
            name='menu',
            field=models.ManyToManyField(related_name='hoadon_vnpay_menu', through='mealmaster.ChiTietHoaDonVNPay', to='mealmaster.menu'),
        ),
        migrations.AddField(
            model_name='payment_vnpay',
            name='ngay_thanh_toan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chitiethoadonvnpay',
            name='mon_an',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mealmaster.monan'),
        ),
    ]
